services:
  app:
    image: myapp
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8081" #http://localhost:8081
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"   # ActiveMQ broker port
      - "8161:8161"     # ActiveMQ web UI  http://localhost:8161/admin
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3307:3306"